name: Android CI on Push and PR to Main

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'true'

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

#      - name: Setup Gradle 4.8
#        uses: gradle/actions/setup-gradle@v4
#        with:
#          gradle-version: "4.8"

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
        with:
          cmdline-tools-version: 9123335

      - uses: nttld/setup-ndk@v1
        with:
          ndk-version: r26d          
          link-to-sdk: true

      - name: Prepare
        working-directory: ./VirtualApp
        run: |
          # echo "android.useAndroidX=true" >> gradle.properties
          # echo "ndk.dir=/usr/local/lib/android/sdk/ndk/27.1.12297006" >> ndk.dir
          ./gradlew tasks
          ./gradlew dependencies

      - name: Build with Gradle
        working-directory: ./VirtualApp
        run: |
          ./gradlew build
